DROP TABLE CAMA;
DROP TABLE HABITACION;
DROP TABLE SE_RECETA_CON;
DROP TABLE SE_COMPONE_DE;
DROP TABLE PRINCIPIO_ACTIVO;
DROP TABLE MEDICAMENTO;
DROP TABLE DONANTE;
DROP TABLE PROPIEDAD_EVENTO;
DROP TABLE EVENTO;
DROP TABLE HISTORIA_CLINICA;
DROP TABLE PACIENTE;
DROP TABLE CREADOR;

CREATE TABLE PACIENTE(
  nombre VARCHAR2(60) NOT NULL,
  nif CHAR(9) PRIMARY KEY,
  nSegSoc CHAR(12) UNIQUE NOT NULL,
  fechaNac DATE NOT NULL,
  direccion VARCHAR2(40) NOT NULL,
  cp NUMBER(5),
  localidad VARCHAR2(30) NOT NULL,
  provincia VARCHAR2(25) NOT NULL,
  telefono NUMBER(9) UNIQUE NOT NULL,
  medicoFamilia VARCHAR2(40),
  centroSalud VARCHAR2(30)
);

CREATE TABLE HISTORIA_CLINICA(
  NHC CHAR(15) PRIMARY KEY,
  nif CHAR(9) NOT NULL,
  
  FOREIGN KEY (nif) REFERENCES PACIENTE
);

CREATE TABLE HABITACION(
  OID_H INTEGER PRIMARY KEY,
  planta INTEGER NOT NULL,
  numero INTEGER NOT NULL
);

CREATE TABLE CAMA(
  OID_CA INTEGER PRIMARY KEY,
  numero INTEGER NOT NULL,
  nif CHAR(9) NOT NULL UNIQUE,
  OID_H INTEGER NOT NULL,
  
  FOREIGN KEY (nif) REFERENCES PACIENTE,
  FOREIGN KEY (OID_H) REFERENCES HABITACION,
  CHECK (numero IN (1, 2))
);

CREATE TABLE CREADOR (
  OID_C INTEGER PRIMARY KEY,
  tipoCreador VARCHAR2(20) NOT NULL,
  dni CHAR(9) UNIQUE,
  nombre VARCHAR2(25),
  especialidad VARCHAR2(25),
  seccion VARCHAR2(25),
  usuario VARCHAR2(25) UNIQUE,
  pass VARCHAR2(25),
  
  CHECK(especialidad IN('Cirugía Hepatobiliar', 'Laparoscopia', 'Endocrinología', null)),
  CHECK(seccion IN('Hematología','Bioquímica clínica','Microbiología','Coproparasitología',
  'Bacteriología','Inmunología','Hormonas','Marcadores tumorales', null)),
  CHECK(tipoCreador IN('Medico', 'Enfermero', 'Laboratorio'))
);

CREATE TABLE MEDICAMENTO (
  OID_M INTEGER PRIMARY KEY,
  nombre VARCHAR2(25) UNIQUE NOT NULL,
  OID_C INTEGER,
  
  FOREIGN KEY(OID_C) REFERENCES CREADOR
);

CREATE TABLE PRINCIPIO_ACTIVO (
  OID_PA INTEGER PRIMARY KEY,
  nombre VARCHAR2(25),
  OID_M INTEGER,
  
  FOREIGN KEY(OID_M) REFERENCES MEDICAMENTO
);

CREATE TABLE EVENTO (
  OID_E INTEGER PRIMARY KEY,
  tipoEvento VARCHAR2(20), --Enumerado
  fechaCreacion TIMESTAMP NOT NULL,
  fechaSuceso TIMESTAMP,
  fechaFinSuceso TIMESTAMP,
  comentarios VARCHAR2(50),
  NHC CHAR(15),
  OID_C INTEGER,
  
  FOREIGN KEY(NHC) REFERENCES HISTORIA_CLINICA,
  FOREIGN KEY(OID_C) REFERENCES CREADOR,
  CHECK (tipoEvento IN('Operacion', 'Prueba', 'Ingreso', 'Eventualidad', 'Deceso', 'Alta', 'Donacion', 'Otro', 'RecetaMedicacion'))
);

CREATE TABLE PROPIEDAD_EVENTO(
  OID_P INTEGER PRIMARY KEY,
  contenido RAW(50),
  OID_E INTEGER NOT NULL,
  
  FOREIGN KEY (OID_E) REFERENCES EVENTO
);

CREATE TABLE SE_RECETA_CON(
  OID_R INTEGER PRIMARY KEY,
  OID_M INTEGER NOT NULL,
  OID_P INTEGER NOT NULL,
  
  FOREIGN KEY (OID_M) REFERENCES MEDICAMENTO,
  FOREIGN KEY (OID_P) REFERENCES PROPIEDAD_EVENTO
);

CREATE TABLE SE_COMPONE_DE(
  OID_D INTEGER PRIMARY KEY,
  OID_M INTEGER NOT NULL,
  OID_PA INTEGER NOT NULL,
  
  FOREIGN KEY (OID_M) REFERENCES MEDICAMENTO,
  FOREIGN KEY (OID_PA) REFERENCES PRINCIPIO_ACTIVO
);

CREATE TABLE DONANTE(
  OID_DO NUMBER,
  DONANTE VARCHAR2(60 BYTE),
  ORGANO VARCHAR2(20 BYTE) NOT NULL,
  NIF CHAR(9),
  OID_P NUMBER,
  
  PRIMARY KEY (OID_DO),
  FOREIGN KEY (OID_P) REFERENCES PROPIEDAD_EVENTO,
  FOREIGN KEY (NIF) REFERENCES PACIENTE
);